### ISSUE TITLE
Replacing/deleting CA certificate doesn't close https connections made based on that CA certificate

### ISSUE THREAD

**Issue by zlukwins** [openbmc/bmcweb#110] opened 2019-11-12 21:12 UTC
Issue is about https connections made based on CA certificate are not closed when CA certificate is replaced or deleted.
Step to reproduce:

1. Install CA certificate (mTLS).
2. Create (and keep alive) https connection based on installed CA certificate.
3. Delete CA certificate installed in first step.
4. Check if connection created in the second step is valid/active.

Current result:
Connection is still valid/active

Expected result:
Connection was closed.

**Comment by edtanous** [comment] 2020-10-19 16:27
Unclear if this was the intended behavior or not, so I've marked as both a bug and an enhancement.  So far as I'm aware, this would be the only place where we shutdown a session because of an authentication change, but we could certainly make that a new behavior.

**Comment by edtanous** [comment] 2023-02-10 20:26
No progress in 3 years.  Clearly this isn't required.  Closing.

**Closed by edtanous** 2023-02-10 20:26 UTC
Labels: bug, enhancement
