### ISSUE TITLE
When the browser is closed, online users can still see the session information.

### ISSUE THREAD

**Issue by ayang05** [openbmc/bmcweb#256] opened 2023-06-17 09:19 UTC
**Describe the bug** A clear and concise description of what the bug is.
When the browser is closed, online users can still see the session information.
**Environment** What OpenBMC platform was this found on? If this was tested in
QEMU, please add
qemu

**Comment by edtanous** [comment] 2023-06-17 22:57
This appears to be working as designed.  Closing a browser window does not invalidate the session.  That is either done on a timeout, or an explicit logout action.

**Comment by edtanous** [comment] 2023-06-21 23:14
No response from submitter.  Working as intended.  If you'd like to discuss further, please feel free to discuss on the mailing list or discord, or, if there's better behavior you'd prefer, please send in a code review through gerrit.

**Closed by edtanous** 2023-06-21 23:14 UTC
