### ISSUE TITLE
redfish validation failing with "Rework Authorization flow" commit

### ISSUE THREAD

**Issue by geissonator** [openbmc/bmcweb#133] opened 2020-07-20 13:04 UTC
All bmcweb bumps starting with https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/30994 are failing HW CI on witherspoon. The Redfish validation fails and we are unable to code update the system after this code gets on the system.

```
ERROR - SchemaURI couldn't call reference link ServiceRoot inside /redfish/v1/$metadata
ERROR - ResourceObject creation: No schema XML for #ServiceRoot.v1_5_0.ServiceRoot /redfish/v1/$metadata#ServiceRoot.ServiceRoot

WARNING - /redfish/v1/ @odata.id: Expected @odata.id to match URI link /redfish/v1
WARNING - SchemaURI /redfish/v1/schema/ServiceRoot_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
WARNING - SchemaURI /redfish/v1/$metadata#ServiceRoot.ServiceRoot was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
WARNING - Unable to find a harddrive stored $metadata at ./SchemaFiles/metadata, defaulting to ServiceRoot_v1.xml
```

```
ERROR - The following schema URIs referenced from $metadata could not be retrieved:

    /redfish/v1/schema/SerialInterface_v1.xml
    /redfish/v1/schema/OemComputerSystem_v1.xml
    /redfish/v1/schema/OutletCollection_v1.xml
    /redfish/v1/schema/OutletGroup_v1.xml
    /redfish/v1/schema/Power_v1.xml
    /redfish/v1/schema/PhysicalContext_v1.xml
    /redfish/v1/schema/SerialInterfaceCollection_v1.xml
    /redfish/v1/schema/Settings_v1.xml
    /redfish/v1/schema/OemSession_v1.xml
    /redfish/v1/schema/VCATEntryCollection_v1.xml
    /redfish/v1/schema/PCIeFunctionCollection_v1.xml
    /redfish/v1/schema/MessageRegistryFileCollection_v1.xml
...
```

**Comment by gtmills** [comment] 2020-07-20 13:25
@feistjj Can you get today ? If not we should merge a revert

**Comment by feistjj** [comment] 2020-07-20 16:27
How can I reproduce this failure?

**Comment by geissonator** [comment] 2020-07-20 17:11
Here's the console output:
```
Test BMC Redfish Using Redfish Service Validator :: Check conforma... #(UTC) 2020/07/20 09:54:46.483767 -    0.115983 - Issuing: rm -rf Redfish-Service-Validator ; git clone --branch master https://github.com/DMTF/Redfish-Service-Validator.git Redfish-Service-Validator
Cloning into 'Redfish-Service-Validator'...
[32m.[0m#(UTC) 2020/07/20 09:54:47.735074 -    1.251308 - Issuing: python3 Redfish-Service-Validator/RedfishServiceValidator.py --ip xxxx:443 --nochkcert --authtype=Session -u root -p CI4ever! --logdir /home/fspcibld/logs/ --debug_logging
First run suggested to create and own local schema files, please download manually or use --schema_pack latest
Alternatively, use the option --prefer_online to skip local schema file checks
The tool will, by default, attempt to download and store XML files to relieve traffic from DMTF/service
Redfish Service Validator, version 1.3.8
Setting up service...
Session successfully created
Constructing metadata...
Writing online XML to file: AccelerationFunction_v1.xml
Writing online XML to file: AccelerationFunctionCollection_v1.xml
Writing online XML to file: AccountService_v1.xml
Writing online XML to file: ActionInfo_v1.xml
Writing online XML to file: AddressPool_v1.xml
Writing online XML to file: AddressPoolCollection_v1.xml
Writing online XML to file: Aggregate_v1.xml
Writing online XML to file: AggregateCollection_v1.xml
Writing online XML to file: AggregationService_v1.xml
Writing online XML to file: AggregationSource_v1.xml
Writing online XML to file: AggregationSourceCollection_v1.xml
Writing online XML to file: Assembly_v1.xml
Writing online XML to file: AttributeRegistry_v1.xml
Writing online XML to file: Bios_v1.xml
Writing online XML to file: BootOption_v1.xml
Writing online XML to file: BootOptionCollection_v1.xml
Writing online XML to file: Certificate_v1.xml
Writing online XML to file: CertificateCollection_v1.xml
Writing online XML to file: CertificateLocations_v1.xml
Writing online XML to file: CertificateService_v1.xml
Writing online XML to file: Chassis_v1.xml
Writing online XML to file: ChassisCollection_v1.xml
Writing online XML to file: Circuit_v1.xml
Writing online XML to file: CircuitCollection_v1.xml
Writing online XML to file: CollectionCapabilities_v1.xml
Writing online XML to file: CompositionService_v1.xml
Writing online XML to file: ComputerSystem_v1.xml
Writing online XML to file: ComputerSystemCollection_v1.xml
Writing online XML to file: ConnectionMethod_v1.xml
Writing online XML to file: ConnectionMethodCollection_v1.xml
Writing online XML to file: Drive_v1.xml
Writing online XML to file: Endpoint_v1.xml
Writing online XML to file: EndpointCollection_v1.xml
Writing online XML to file: EthernetInterface_v1.xml
Writing online XML to file: EthernetInterfaceCollection_v1.xml
Writing online XML to file: Event_v1.xml
Writing online XML to file: EventDestination_v1.xml
Writing online XML to file: EventDestinationCollection_v1.xml
Writing online XML to file: EventService_v1.xml
Writing online XML to file: ExternalAccountProvider_v1.xml
Writing online XML to file: ExternalAccountProviderCollection_v1.xml
Writing online XML to file: Fabric_v1.xml
Writing online XML to file: FabricAdapter_v1.xml
Writing online XML to file: FabricAdapterCollection_v1.xml
Writing online XML to file: FabricCollection_v1.xml
Writing online XML to file: Facility_v1.xml
Writing online XML to file: FacilityCollection_v1.xml
Writing online XML to file: HostInterface_v1.xml
Writing online XML to file: HostInterfaceCollection_v1.xml
Writing online XML to file: IPAddresses_v1.xml
Writing online XML to file: Job_v1.xml
Writing online XML to file: JobCollection_v1.xml
Writing online XML to file: JobService_v1.xml
Writing online XML to file: JsonSchemaFile_v1.xml
Writing online XML to file: JsonSchemaFileCollection_v1.xml
Writing online XML to file: LogEntry_v1.xml
Writing online XML to file: LogEntryCollection_v1.xml
Writing online XML to file: LogService_v1.xml
Writing online XML to file: LogServiceCollection_v1.xml
Writing online XML to file: Manager_v1.xml
Writing online XML to file: ManagerAccount_v1.xml
Writing online XML to file: ManagerAccountCollection_v1.xml
Writing online XML to file: ManagerCollection_v1.xml
Writing online XML to file: ManagerNetworkProtocol_v1.xml
Writing online XML to file: MediaController_v1.xml
Writing online XML to file: MediaControllerCollection_v1.xml
ConnectionError on /redfish/v1/schema/Memory_v1.xml: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)
SchemaURI /redfish/v1/schema/Memory_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
Metadata: failure opening schema /redfish/v1/schema/Memory_v1.xml of type Memory
ConnectionError on /redfish/v1/schema/MemoryChunks_v1.xml: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)
SchemaURI /redfish/v1/schema/MemoryChunks_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
Metadata: failure opening schema /redfish/v1/schema/MemoryChunks_v1.xml of type MemoryChunks
ConnectionError on /redfish/v1/schema/MemoryChunksCollection_v1.xml: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)
SchemaURI /redfish/v1/schema/MemoryChunksCollection_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
Metadata: failure opening schema /redfish/v1/schema/MemoryChunksCollection_v1.xml of type MemoryChunksCollection
...
SchemaURI /redfish/v1/schema/OemSession_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
Metadata: failure opening schema /redfish/v1/schema/OemSession_v1.xml of type OemSession
SchemaURI /redfish/v1/schema/Memory_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
SchemaURI /redfish/v1/schema/Memory_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
SchemaURI /redfish/v1/schema/Memory_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
SchemaURI /redfish/v1/schema/Memory_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
...
SchemaURI /redfish/v1/schema/OemSession_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
SchemaURI /redfish/v1/schema/OemSession_v1.xml was unable to be called, defaulting to local storage in ./SchemaFiles/metadata
Redfish Version of Service: 1.9.0
ConfigURI: xxxxxx:443
System Info: No desc
authtype: Session
cachefilepath: ./cache
cachemode: Off
certificatecheck: False
configuri: https://xxxxx2:443
csv_report: False
debug_logging: True
forceauth: False
linklimit: {'LogEntry': 20}
localonlymode: False
logpath: /home/xxxxxxx/logs/
metadatafilepath: ./SchemaFiles/metadata
oemcheck: True
preferonline: False
sample: 0
schemasuffix: _v1.xml
servicemode: False
timeout: 30
uricheck: False
username: root
usessl: True
Start time: 07/20/20 - 09:54:48
```

**Comment by gtmills** [comment] 2020-07-20 17:12
@feistjj https://github.com/openbmc/openbmc-test-automation/blob/79bf27331f4f9b704e77cbec61df4152cfe966d9/redfish/dmtf_tools/Redfish_Service_Validator.robot#L16
Are you using basic auth ?

**Comment by feistjj** [comment] 2020-07-20 17:16
No, I'm using this config:
```
[SystemInformation]
TargetIP = XX.XX.XX.XX
SystemInfo = James
UserName = root
Password = 0penBmc
AuthType = Session 
ForceAuth = False
Token = 
UseSSL = True
CertificateCheck = False
CertificateBundle = 

[Options]
MetadataFilePath = /home/james/redfish_metadata
Schema_Pack = 
OemCheck = True
CacheMode = Off
CacheFilePath = 
SchemaSuffix = _v1.xml
Timeout = 30
HttpProxy = 
HttpsProxy = 
LocalOnlyMode = True 
ServiceMode = False
PreferOnline = False
LinkLimit = LogEntry:2
Sample = 3

[Validator]
PayloadMode = Default
PayloadFilePath = 
LogPath = ./logs/james
```
I'll try using those args

**Comment by feistjj** [comment] 2020-07-20 17:24
@gtmills  those args work for me

Although from @geissonator it looks like you are hitting the timeout for some reason. I would have assumed 15 seconds to be long enough, but 

> ConnectionError on /redfish/v1/schema/Memory_v1.xml: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)

It does look like you're hitting the timeout though, can you pull down /redfish/v1/schema/Memory_v1.xml on one of your systems and see how long it takes in the inspect window?

**Comment by feistjj** [comment] 2020-07-20 20:40
I *think* this might fix it: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34898

That being said, I don't have access to a system that fails in this exact manner.

**Comment by geissonator** [comment] 2020-07-20 21:42
We didn't test with the bmcweb commit on the system, but just doing the get of Memory_v1.xml was very fast for us using master code:
```
time curl -k https://$bmc/redfish/v1/schema/Memory_v1.xml
...
real    0m0.352s
user    0m0.070s
sys     0m0.054s
```

**Comment by gtmills** [comment] 2020-07-20 22:57
James do you want to try to wipe your MetadataFilePath = /home/james/redfish_metadata and see if that recreates?

**Comment by geissonator** [comment] 2020-07-20 23:59
I gave the fix a quick run in QEMU but really didn't seem to help. I verified that running the validator against the current bmcweb merged into openbmc master/master passed as expected (-2 power supply tests that always fail)

**Comment by feistjj** [comment] 2020-07-21 16:04
@gtmills when I used the args from the script I used a different path

@geissonator so its passing now?

**Comment by geissonator** [comment] 2020-07-22 14:19
Hey James, the validator tests are now passing! But we're still seeing the issue where when we try to code update the system after this commit gets on the system, it fails. Our images are large and our network is slow, so I think we need to increase the time allowed on the pushing of the images? @anoo1 remembered a commit where we had bmcweb monitor for activity and would allow a connection to stay opened as long as data was flowing.

**Comment by anoo1** [comment] 2020-07-22 14:26
For reference this is the commit that fixed big uploads: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/28335

Seems the function was modified as part of the latest change set, maybe that piece needs to be revisited or left the same.

**Comment by feistjj** [comment] 2020-07-22 15:15
Ok I'll add something like that back today

**Comment by feistjj** [comment] 2020-07-22 15:16
Ok I think we can add that back now that we check if we are authenticated before read, I'll do that today

**Comment by feistjj** [comment] 2020-07-22 15:24
How long is "really long"? Now that we have 2 timers for logged-in and logged-out users, we can increase the timer for logged-out users to anything

**Comment by geissonator** [comment] 2020-07-22 15:34
Looking through the last few runs, it seems like the upload is only taking about 8 seconds. Our network can def fluctuate a bit though. We do have some concern that emmc support is on it's way and we're talking much larger images to upload there. So anything that allows a connection to stay open as long as data is flowing would be great.

**Comment by feistjj** [comment] 2020-07-22 15:58
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34972

**Comment by edtanous** [comment] 2020-07-22 16:53
The core of this issue is that we need a chunked upload mechanism.  The full bmc image (32 or 64MB) is already too big to be holding in memory in one shot, which is how bmcweb was originally designed because it was easier, and images at the time were smaller.  The long term intent was to provide a streaming interface (kinda like the websocket handler) so we could stream the file directly to disk, without consuming lots of memory in the meantime, and we can rate limit based on what the BMC capabilities are by streaming the file to the filesystem.  I suspect as bmcs move to EMMC, and the file uploads get bigger, that infrastructure will need to be built.  We can't just keep increasing the timeouts, or implementing goofy non-standard rate tracking mechanisms, because we will always have problems with someones use case (what if I'm on a 56k modem uploading a 5GB file for example).  Many CVEs have been published on many web servers that try to implement bitrate-based handling.  We need to not go down that path.
The MIME parser should be the hard part of the above, which is already in review/in progress.

**Comment by geissonator** [comment] 2020-07-23 14:08
Unfortunately, we still have issues code updating the system, even with the latest patch.

```
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
 
We see nothing in the bmc journal indicating an issue.

**Comment by feistjj** [comment] 2020-07-23 16:17
Dumb question, are you uploading to the new image, and then attempting to upload the image again? Are you stuck at an old 'bad version' that the upload isn't working for?

**Comment by gtmills** [comment] 2020-08-25 00:17
This has been resolved. Closing. @geissonator Please reopen if I wrongly closed.

**Closed by gtmills** 2020-08-25 00:17 UTC
