### ISSUE TITLE
SSL handshake failed (5)

### ISSUE THREAD

**Issue by chandu-tmba** [openbmc/bmcweb#197] opened 2021-04-19 14:59 UTC
while running apache benchmark tool with openbmc redfish , i am facing ssl handshake issue

Nuvoton
OpenBMC  v1.9

1. Run the command 'ab -s 50 -n 25 -c 1 -A root:0penBmc https:{ip}/redfish/v1/<uri's> , actually i am using  shell script , which contains these kind of commands, 
2. See error SSL handshake failed (5).
3. Expected behavior was 'ssl errors should not come'

**Comment by edtanous** [comment] 2021-04-19 19:38
Have you uploaded a valid SSL certificate to your BMC?

**Comment by chandu-tmba** [comment] 2021-04-21 14:00
no, havent uploaded any certificate

**Comment by edtanous** [comment] 2021-04-21 15:08
That is why your test can't connect;  You will either need to upload a valid certificate, or tell ab to ignore the certificate validity.

This appears to be a bug in your test setup, not in bmcweb.  Closing.  Feel free to reopen if there is something that appears to be incorrect with bmcweb, but for now, it appears to be working as designed.

**Closed by edtanous** 2021-04-21 15:08 UTC

**Comment by chandu-tmba** [comment] 2021-05-04 14:13
by default ,one https certificare is there in bmc, under /etc/ssl/certs/https/ folder . so i am not uploading any https certificate, validaity is almost one year for this certificate.  i am facing issue only when ever i ran abtool command in shell script for loop , when i am giving single abtol  request manually i am not facing any issue.

**Comment by chandu-tmba** [comment] 2021-05-04 14:41
ab  -s 50 -n 25 -c 1 -A root:0penBmc https://<IP>/redfish/v1/Systems  

this is the sample URI using in shell script for loop

**Comment by chandu-tmba** [comment] 2021-05-04 14:53
please reopen the issue

**Comment by edtanous** [comment] 2021-05-04 14:55
Please upload a valid certificate to your BMC, or set up ab to ignore certificate errors as instructed.  If the problem persists after you've done so, I will reopen the issue.

The BMC certificate is self-signed by default, which will cause errors if you try to connect clients that are expecting a valid certificate.

**Comment by chandu-tmba** [comment] 2021-05-13 13:24
still getting same error, uplaoded vlaid ssl certificate via web ui ,

certificate creation steps followed 
1. openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout selfsigned.key -out selfsigned.crt  -subj "/C=SI/ST=Ljubljana/L=Ljubljana/O=Security/OU=IT Department/CN=www.example.com"
2. cat selfsigned.crt selfsigned.key > selfsigned.pem

shell script which is throwing error
#!/bin/bash
a=0

while [ $a -lt 100 ]
do
  echo "Looping ... number $a" 
  ab  -s 30 -n 25 -c 1 -A root:0penBmc https://10.0.124.89/redfish/v1/
  a=`expr $a + 1`
done

**Comment by chandu-tmba** [comment] 2021-05-13 13:27
i think this is something to do with ciphersuite 

SSL/TLS Handshake [Start] before SSL initialization
SSL/TLS State [connect] before SSL initialization
SSL/TLS State [connect] SSLv3/TLS write client hello
SSL handshake failed (5).
SSL/TLS Handshake [Start] before SSL initialization
SSL/TLS State [connect] before SSL initialization
SSL/TLS State [connect] SSLv3/TLS write client hello
SSL handshake failed (5).
SSL/TLS Handshake [Start] before SSL initialization
SSL/TLS State [connect] before SSL initialization
SSL/TLS State [connect] SSLv3/TLS write client hello
SSL/TLS State [connect] SSLv3/TLS write client hello
SSL/TLS State [connect] SSLv3/TLS read server hello
SSL/TLS State [connect] SSLv3/TLS read server certificate
SSL/TLS State [connect] SSLv3/TLS read server key exchange
SSL/TLS State [connect] SSLv3/TLS read server done
SSL/TLS State [connect] SSLv3/TLS write client key exchange
SSL/TLS State [connect] SSLv3/TLS write change cipher spec
SSL/TLS State [connect] SSLv3/TLS write finished
SSL/TLS State [connect] SSLv3/TLS write finished
SSL/TLS State [connect] SSLv3/TLS read server session ticket
SSL/TLS State [connect] SSLv3/TLS read change cipher spec
SSL/TLS State [connect] SSLv3/TLS read finished
SSL/TLS Handshake [Done] SSL negotiation finished successfully

this is the debug log, after client write hello, i am getting ssl handshake failure

**Comment by chandu-tmba** [comment] 2021-05-13 13:38
this is the o/p for supported  ciphersuite supported for bmcweb
root@ubuntu-OptiPlex-5080:/home/ubuntu/cipherscan/cipherscan# ./cipherscan 10.0.124.81:443
.....
prio  ciphersuite                  protocols  pfs_keysize
1     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2    ECDH,P-521,521bits
2     ECDHE-RSA-AES256-SHA384      TLSv1.2    ECDH,P-521,521bits
3     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2    ECDH,P-521,521bits
4     ECDHE-RSA-AES128-SHA256      TLSv1.2    ECDH,P-521,521bits

Certificate: Not a match, UNTRUSTED, 2048 bit, sha256WithRSAEncryption signature
TLS ticket lifetime hint: 7200
OCSP stapling: not supported
WARNING - None of the CNs match the hostname given
Here is the list of common names found in the certificate
test

**Comment by chandu-tmba** [comment] 2021-05-13 13:40
even i tried creating CN name with  hostname also , but still it is not working , i think the issue is not about  certificate validity

**Comment by chandu-tmba** [comment] 2021-05-13 13:44
the problem here is , i am facing this issue only when  i am running ab command in loop using shell script, if i am running it once in command line it is working fine

**Comment by chandu-tmba** [comment] 2021-05-13 13:44
the problem here is , i am facing this issue only when  i am running ab command in loop using shell script, if i am running it once in command line it is working fine

**Comment by chandu-tmba** [comment] 2021-05-17 12:51
please reopen the issue

**Comment by edtanous** [comment] 2021-05-18 03:48
> the problem here is , i am facing this issue only when i am running ab command in loop using shell script, if i am running it once in command line it is working fine

This wasn't in your steps to reproduce originally.  If it had been, we likely would've given you the answer faster.


Looking at your script, I'm going to guess that ab isn't closing the connections properly and bmcweb  is hitting its connection limit.  The connection limits are by design to protect the rest of the BMC, and based on your scripts seem to be working properly, as you're spinning up 25 requests per loop.  Unless there's more information here that leads me to believe this is an actual issue, or someone else reports the same, I'm going to leave this closed, as it sounds like you were able to get ab to work per your original instructions.

With that said, if you've root caused this further and this this is a coding bug, feel free to provide more information or ideally a patch to fix the behavior you're seeing, but with the information above, this looks like bmcweb is working.

> WARNING - None of the CNs match the hostname given
> Here is the list of common names found in the certificate
> test

FYI This would imply that you haven't uploaded a valid and trusted certificate, although your problems seem to lie elsewhere.

**Comment by chandu-tmba** [comment] 2021-06-10 13:14
i checked once again , i enabled debugging and found this error in log
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "authorization.hpp":117] [AuthMiddleware] X-Auth-Token authentication
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "authorization.hpp":132] [AuthMiddleware] Cookie authentication
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "authorization.hpp":42] [AuthMiddleware] Basic authentication
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "authorization.hpp":72] [AuthMiddleware] Authenticating user: root
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "authorization.hpp":73] [AuthMiddleware] User IPAddress: ::ffff:172.31.1.252
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: pam_succeed_if(webserver:auth): requirement "user ingroup redfish" was met by user "root"
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "timer_queue.hpp":48] timer add inside: 0x1d925a0 456
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":776] 0x1edc500 timer added: 0x1d925a0 456
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":586] Starting slow deadline
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":596] QueryParams:
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":621] 0x1edc500 doRead
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":628] 0x1edc500 async_read 0 Bytes
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":722] 0x1edc500 timer cancelled: 0x1d925a0 456
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "timer_queue.hpp":48] timer add inside: 0x1d925a0 457
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":776] 0x1edc500 timer added: 0x1d925a0 457
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":722] 0x1edc500 timer cancelled: 0x1d925a0 457
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [INFO "http_connection.hpp":351] Request:  0x1edc500 HTTP/1.1 GET /redfish/v1/Systems/system/Netwo
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "routing.hpp":1285] Matched rule '/redfish/v1/Systems/system/NetworkInterfaces/' 2 / 4
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "routing.hpp":1322] userName = root userRole = priv-admin
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [ERROR "systems.hpp":3618] DBUS error: no matched iface generic:5
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_response.hpp":118] calling completion handler
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_response.hpp":121] completion handler was valid
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [INFO "http_connection.hpp":435] Response: 0x1edc500 /redfish/v1/Systems/system/NetworkInterfaces
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "timer_queue.hpp":48] timer add inside: 0x1d925a0 458
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":776] 0x1edc500 timer added: 0x1d925a0 458
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":680] 0x1edc500 doWrite
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":688] 0x1edc500 async_write 797 bytes
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":722] 0x1edc500 timer cancelled: 0x1d925a0 458
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":706] 0x1edc500 Clearing response
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_response.hpp":99] 0x1ede750 Clearing response containers
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":519] 0x1edc500 doReadHeaders
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [ERROR "http_connection.hpp":527] 0x1edc500 async_read_header 0 Bytes
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [ERROR "http_connection.hpp":533] 0x1edc500 Error while reading: end of stream
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":551] 0x1edc500 from read(1)
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":271] http cpnnection closed
Jun 10 12:14:19 AMI06fe1fa4694f bmcweb[354]: (2021-06-10 12:14:19) [DEBUG "http_connection.hpp":276] 0x1edc500 Connection closed, total 2
