### ISSUE TITLE
bmcweb truncates value if an out-of-range byte number is used

### ISSUE THREAD

**Issue by anoo1** [openbmc/bmcweb#101] opened 2019-07-31 17:29 UTC
The Priority property value is defined as a byte, and with the previous REST server, it'd fail as follows when an out-of-range value (greater than 255) was passed:
```
$ curl -b cjar -k -H 'Content-Type: application/json' -X PUT -d '{"data":300}' https://$BMC_IP/xyz/openbmc_project/software/cf421794/attr/Priority
{
  "data": {
    "description": "Failed to convert 300 to type y"
  },
  "message": "403 Forbidden",
  "status": "error"
}
```

But with bmcweb, success is returned, and the priority value is set to 44 when 300 is used:
```
$ curl -k -H "X-Auth-Token: $bmc_token" -X PUT -d '{"data":300}' https://$BMC_IP/xyz/openbmc_project/software/48fbc8d0/attr/Priority
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

$ curl -k -H "X-Auth-Token: $bmc_token" -XGET https://${BMC_IP}/xyz/openbmc_project/software/48fbc8d0
{
  "data": {
    "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active",
    "Path": "",
    "Priority": 44,
```

**Comment by spinler** [comment] 2019-07-31 17:43
that's just a cast:  300 = 0x12C, so 300 & 0xFF = 0x2C = 44

**Comment by edtanous** [comment] 2019-07-31 17:48
Could definitely be improved with std::numeric_limits range checks.  The Redfish ReadJson function does some similar things here: 

https://github.com/openbmc/bmcweb/blob/3d958bbc6cdc66e983d3a8c3f056d55bfc128276/redfish-core/include/utils/json_utils.hpp#L82

I suspect that code could be mostly reused to add that to the dbus endpoints..

**Comment by anoo1** [comment] 2019-07-31 18:24
Thanks, that helps. Will look into adding the range check to the dbus endpoint.

**Comment by edtanous** [comment] 2019-08-16 22:39
This appears to be a more generic duplicate of https://github.com/openbmc/bmcweb/issues/42

**Closed** 2019-08-27 18:17 UTC
