### ISSUE TITLE
Segmentation fault when /subscribe request is called

### ISSUE THREAD

**Issue by esm** [openbmc/bmcweb#213] opened 2021-06-24 18:31 UTC
When I run webui-vue and login, I get the Proxy error in the image below which says that it cannot proxy the subscribe request from my webui-vue which runs on port 8000 to bmcweb which runs on port 18080. The error comes from line 1187 in  bmcweb/http/routing.hpp
I am running on Ubuntu

![webui-vuee](https://user-images.githubusercontent.com/71355487/123311642-66b2c500-d4f5-11eb-8421-54d8771a6baf.PNG)
![bmcweb_subscribe](https://user-images.githubusercontent.com/71355487/123311385-205d6600-d4f5-11eb-9988-a1edf1faca5f.PNG)

**Comment by edtanous** [comment] 2021-06-24 18:35
Duplicate of #212.  Please update your bug there instead of opening a new one.

**Closed by edtanous** 2021-06-24 18:35 UTC
