### ISSUE TITLE
Redfish: DHCP Enable and Disable not working

### ISSUE THREAD

**Issue by prkatti1** [openbmc/bmcweb#127] opened 2020-06-05 07:25 UTC
Enabling and disabling DHCP via Redfish is not working. Getting 500 error.

Verson info:
cat /etc/os-release
ID=openbmc-witherspoon
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.8.0-rc1"
VERSION_ID=2.8.0-rc1-0-g35a774200
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.8.0-rc1"
BUILD_ID="2.8.0-rc1"
OPENBMC_TARGET_MACHINE="witherspoon"

curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"DHCPv4" : {"DHCPEnabled":false}}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_0_0.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.4.0.InternalError",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.4.0.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }

**Comment by jk-ozlabs** [comment] 2020-06-25 08:36
Reproduced on the s2600wf platform too, I'll do some investigating.

**Comment by jk-ozlabs** [comment] 2020-06-25 09:33
It looks like the DHCP data isn't correct in the first place; on my DHCP-enabled configuration, I get:

```
  "DHCPv4": {
    "DHCPEnabled": false,
    "UseDNSServers": true,
    "UseDomainName": true,
    "UseNTPServers": true
  },
```

(this is before doing any `PATCH` operation)

**Comment by jk-ozlabs** [comment] 2020-06-25 09:58
Looks like we're out of sync between phosphor-networkd and bmcweb; the change in 12162be363f1 isn't supported by phosphor-networkd (and violates the current phosphor-dbus-interfaces spec).

**Comment by geissonator** [comment] 2020-06-25 13:27
I think @Howitzer105mm has some code coming to fix this. He's testing the different pieces with https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/33765

**Comment by Howitzer105mm** [comment] 2020-06-25 16:14
Commit 33765 combines:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-ipmid/+/27278
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/24666
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/33689

BMCWeb and phosphor-dbus-interfaces were in sync at one time in the long distant past. At the time only phosphor-network was needed to be merged to make the Redfish DHCP features operational. 
27278 is pledged to be merged by the maintainer as soon as PDI, and PN are merged.
I just need closure on 24666.

**Comment by jk-ozlabs** [comment] 2020-06-26 01:38
OK, super, I've added a couple of reviews on those, all look good.

We should work out a strategy to fix this for the 2.8 branch in a non-intrusive way; should we revert the original bmcweb change there?

**Comment by Howitzer105mm** [comment] 2020-06-26 19:29
I'm not sure what your concern is.
IMO this is an intrusive change. Why does it matter which branch we intrude upon?

**Comment by jk-ozlabs** [comment] 2020-06-30 02:06
Because we're attempting to stabilise 2.8, no?

**Comment by edtanous** [comment] 2020-10-19 16:22
The 3 commits in question have been merged.  I'm assuming this resolved the issue.  If someone wants to backport to 2.8, that would be fine.

**Closed by edtanous** 2020-10-19 16:22 UTC
